### ISSUE TITLE
大佬出现这样的问题怎么解决啊

### ISSUE THREAD

**Issue by yuhualuojin** [nonPointer/ClashHelper#1]
![image](https://user-images.githubusercontent.com/68735592/173521354-cd216c95-6067-4baa-9c17-1ddd3ed2678d.png)
大佬运行出现这样

**Comment by nonPointer** [comment]
将第 67 行的 `[str]` 删除即可。
你的 Python 版本可能低于 3.9，无法识别这种语法。

**Comment by yuhualuojin** [comment]
好的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月14日(星期二) 下午3:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [nonPointer/ClashHelper] 大佬出现这样的问题怎么解决啊 (Issue #1)





 
将第 67 行的 [str] 删除即可。
 你的 Python 版本可能低于 3.9，无法识别这种语法。

**Comment by yuhualuojin** [comment]
![image](https://user-images.githubusercontent.com/68735592/173524442-c11d60ae-d4c4-4cbd-8beb-05a79805768f.png)
这个样子了

**Comment by nonPointer** [comment]
你的 `sites.yaml` 不是标准的 yaml 格式，或者插入了非 utf-8 的字符导致报错。

**Comment by yuhualuojin** [comment]
![image](https://user-images.githubusercontent.com/68735592/173528530-d4db42a8-89c4-43ab-a0e1-b77e702fb64d.png)
没错啊直接复制你的那个来的

**Comment by nonPointer** [comment]
无法复现
